### ISSUE TITLE
Embeds are not consistent

### ISSUE THREAD

**Issue by refractored** [refractored/submarine-delivery#14]
The image in the upper right corner either is blank or shows the command executor's profile picture.

**Comment by Baconing** [comment]
The only time an embed worked was when it showed the executor's profile picture, however this was incorrect code and was due to incorrect code as the author icon is supposed to be the bot's profile picture.

This seems to be an error with the way the session is passed in the slash command event handler, as it should work fine because it doesn't use the slash command event at all, and the code is the same as when we used legacy commands.
